//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from math.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="mathParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ImathVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] mathParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] mathParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] mathParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] mathParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.equ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqu([NotNull] mathParser.EquContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.pi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPi([NotNull] mathParser.PiContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitE([NotNull] mathParser.EContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] mathParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.logarithm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogarithm([NotNull] mathParser.LogarithmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.log"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLog([NotNull] mathParser.LogContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.ln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLn([NotNull] mathParser.LnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.trig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrig([NotNull] mathParser.TrigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.sin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSin([NotNull] mathParser.SinContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.cos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCos([NotNull] mathParser.CosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.tan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTan([NotNull] mathParser.TanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.sinh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinh([NotNull] mathParser.SinhContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.cosh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCosh([NotNull] mathParser.CoshContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.tanh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTanh([NotNull] mathParser.TanhContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.arcsin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArcsin([NotNull] mathParser.ArcsinContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.arccos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArccos([NotNull] mathParser.ArccosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.arctan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArctan([NotNull] mathParser.ArctanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.arcsinh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArcsinh([NotNull] mathParser.ArcsinhContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.arccosh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArccosh([NotNull] mathParser.ArccoshContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.arctanh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArctanh([NotNull] mathParser.ArctanhContext context);
}
